---
- name: restart consul
  systemd:
    daemon_reload: true
    name: consul-template
    state: restarted
  become: true
  tags: consul

- name: reload consul
  systemd:
    name: consul
    state: reloaded
  become: true
  tags: consul

- name: reload ufw
  systemd:
    name: ufw
    state: reloaded
  tags: consul
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags: consul
  become: true